//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtranetAppsOmniSerca.WSVendedores {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="WSVendedores.VendedoresSoap")]
    public interface VendedoresSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetBancos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBancos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetClienteById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetClienteById(long pUsr, long pCliID, long pAcc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetClientes(long pUsr, long pAcc, long pVis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetCondicionesIva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCondicionesIva();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetFirma", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFirma(long pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetFormasPago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFormasPago();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetProductos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetProductos(long pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetRubros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetRubros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetSolicitudDigitalizada", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSolicitudDigitalizada(long pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetTarjetasCredito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTarjetasCredito();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetTiposCuentas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTiposCuentas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetUsuarioValidacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUsuarioValidacion(long pUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetVendedores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetVendedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.GetVendedoresV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetVendedoresV2(long pUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.SetClienteActivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SetClienteActivo(long pPotId, long pUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.SetClientePotencial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SetClientePotencial(
                    long pId, 
                    string pCodCli, 
                    string pTitRaz, 
                    string pTitFan, 
                    string pCuit, 
                    long pActCli, 
                    string pSitIva, 
                    long pNroDoc, 
                    long pFecIng, 
                    long pFecVto, 
                    long pUsr, 
                    string pNroCto, 
                    string pTitDm1, 
                    long pTitDm2, 
                    long pTitDm3, 
                    string pTitDm4, 
                    string pTitRef, 
                    string pTitEt1, 
                    string pTitEt2, 
                    string pTitLat, 
                    string pTitLon, 
                    string pTitCP, 
                    long pTitLoc, 
                    string pTitTel, 
                    string pccNom, 
                    string pccCar, 
                    string pccTel, 
                    string pccMail, 
                    string pccTel2, 
                    string pccMail2, 
                    string pFacDm1, 
                    long pFacDm2, 
                    long pFacDm3, 
                    string pFacDm4, 
                    string pFacRef, 
                    string pFacEt1, 
                    string pFacEt2, 
                    string pFacLat, 
                    string pFacLon, 
                    string pFacCP, 
                    long pFacLoc, 
                    decimal pImpMen, 
                    decimal pImpAdl, 
                    long pPrxPag, 
                    long pFpg, 
                    string pTarId, 
                    string pTarNro, 
                    long pTarVto, 
                    string pTarTit, 
                    string pTarDoc, 
                    string pCtaBco, 
                    long pCtaTip, 
                    string pCtaNro, 
                    string pCtaRaz, 
                    string pCtaCti, 
                    string pCtaCbu, 
                    long pDomLegCob, 
                    long pPrep, 
                    string pLisPro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.SetFirma", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SetFirma(long pId, string pVal, string pExt, long pUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Vendedores.ValidateCUIT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ValidateCUIT(long pUsr, string pCti, long pCli);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VendedoresSoapChannel : ExtranetAppsOmniSerca.WSVendedores.VendedoresSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VendedoresSoapClient : System.ServiceModel.ClientBase<ExtranetAppsOmniSerca.WSVendedores.VendedoresSoap>, ExtranetAppsOmniSerca.WSVendedores.VendedoresSoap {
        
        public VendedoresSoapClient() {
        }
        
        public VendedoresSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VendedoresSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendedoresSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendedoresSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetBancos() {
            return base.Channel.GetBancos();
        }
        
        public System.Data.DataSet GetClienteById(long pUsr, long pCliID, long pAcc) {
            return base.Channel.GetClienteById(pUsr, pCliID, pAcc);
        }
        
        public System.Data.DataSet GetClientes(long pUsr, long pAcc, long pVis) {
            return base.Channel.GetClientes(pUsr, pAcc, pVis);
        }
        
        public System.Data.DataSet GetCondicionesIva() {
            return base.Channel.GetCondicionesIva();
        }
        
        public string GetFirma(long pId) {
            return base.Channel.GetFirma(pId);
        }
        
        public System.Data.DataSet GetFormasPago() {
            return base.Channel.GetFormasPago();
        }
        
        public System.Data.DataSet GetProductos(long pId) {
            return base.Channel.GetProductos(pId);
        }
        
        public System.Data.DataSet GetRubros() {
            return base.Channel.GetRubros();
        }
        
        public System.Data.DataSet GetSolicitudDigitalizada(long pId) {
            return base.Channel.GetSolicitudDigitalizada(pId);
        }
        
        public System.Data.DataSet GetTarjetasCredito() {
            return base.Channel.GetTarjetasCredito();
        }
        
        public System.Data.DataSet GetTiposCuentas() {
            return base.Channel.GetTiposCuentas();
        }
        
        public System.Data.DataSet GetUsuarioValidacion(long pUsr) {
            return base.Channel.GetUsuarioValidacion(pUsr);
        }
        
        public System.Data.DataSet GetVendedores() {
            return base.Channel.GetVendedores();
        }
        
        public System.Data.DataSet GetVendedoresV2(long pUsr) {
            return base.Channel.GetVendedoresV2(pUsr);
        }
        
        public System.Data.DataSet SetClienteActivo(long pPotId, long pUsr) {
            return base.Channel.SetClienteActivo(pPotId, pUsr);
        }
        
        public System.Data.DataSet SetClientePotencial(
                    long pId, 
                    string pCodCli, 
                    string pTitRaz, 
                    string pTitFan, 
                    string pCuit, 
                    long pActCli, 
                    string pSitIva, 
                    long pNroDoc, 
                    long pFecIng, 
                    long pFecVto, 
                    long pUsr, 
                    string pNroCto, 
                    string pTitDm1, 
                    long pTitDm2, 
                    long pTitDm3, 
                    string pTitDm4, 
                    string pTitRef, 
                    string pTitEt1, 
                    string pTitEt2, 
                    string pTitLat, 
                    string pTitLon, 
                    string pTitCP, 
                    long pTitLoc, 
                    string pTitTel, 
                    string pccNom, 
                    string pccCar, 
                    string pccTel, 
                    string pccMail, 
                    string pccTel2, 
                    string pccMail2, 
                    string pFacDm1, 
                    long pFacDm2, 
                    long pFacDm3, 
                    string pFacDm4, 
                    string pFacRef, 
                    string pFacEt1, 
                    string pFacEt2, 
                    string pFacLat, 
                    string pFacLon, 
                    string pFacCP, 
                    long pFacLoc, 
                    decimal pImpMen, 
                    decimal pImpAdl, 
                    long pPrxPag, 
                    long pFpg, 
                    string pTarId, 
                    string pTarNro, 
                    long pTarVto, 
                    string pTarTit, 
                    string pTarDoc, 
                    string pCtaBco, 
                    long pCtaTip, 
                    string pCtaNro, 
                    string pCtaRaz, 
                    string pCtaCti, 
                    string pCtaCbu, 
                    long pDomLegCob, 
                    long pPrep, 
                    string pLisPro) {
            return base.Channel.SetClientePotencial(pId, pCodCli, pTitRaz, pTitFan, pCuit, pActCli, pSitIva, pNroDoc, pFecIng, pFecVto, pUsr, pNroCto, pTitDm1, pTitDm2, pTitDm3, pTitDm4, pTitRef, pTitEt1, pTitEt2, pTitLat, pTitLon, pTitCP, pTitLoc, pTitTel, pccNom, pccCar, pccTel, pccMail, pccTel2, pccMail2, pFacDm1, pFacDm2, pFacDm3, pFacDm4, pFacRef, pFacEt1, pFacEt2, pFacLat, pFacLon, pFacCP, pFacLoc, pImpMen, pImpAdl, pPrxPag, pFpg, pTarId, pTarNro, pTarVto, pTarTit, pTarDoc, pCtaBco, pCtaTip, pCtaNro, pCtaRaz, pCtaCti, pCtaCbu, pDomLegCob, pPrep, pLisPro);
        }
        
        public System.Data.DataSet SetFirma(long pId, string pVal, string pExt, long pUsr) {
            return base.Channel.SetFirma(pId, pVal, pExt, pUsr);
        }
        
        public System.Data.DataSet ValidateCUIT(long pUsr, string pCti, long pCli) {
            return base.Channel.ValidateCUIT(pUsr, pCti, pCli);
        }
    }
}
