//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtranetAppsOmniSerca.WSProveedoresCuentas {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="WSProveedoresCuentas.ProveedoresCuentasSoap")]
    public interface ProveedoresCuentasSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.ProveedoresCuentas.GetCuentaCorrienteV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCuentaCorrienteV2(long pUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.ProveedoresCuentas.GetProveedores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.ProveedoresCuentas.GetUsuarioValidacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUsuarioValidacion(long pUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.ProveedoresCuentas.SetComprobante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SetComprobante(long pCtaId, long pNroCae, long pFecEmi, string pTipCmp, string pNroCmp, decimal pImp, long pUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.ProveedoresCuentas.SetComprobanteV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SetComprobanteV2(string pNroOp, string pTipCmp, string pNroCmp, long pFecEmi, long pNroCae, decimal pImp, long pUsr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProveedoresCuentasSoapChannel : ExtranetAppsOmniSerca.WSProveedoresCuentas.ProveedoresCuentasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProveedoresCuentasSoapClient : System.ServiceModel.ClientBase<ExtranetAppsOmniSerca.WSProveedoresCuentas.ProveedoresCuentasSoap>, ExtranetAppsOmniSerca.WSProveedoresCuentas.ProveedoresCuentasSoap {
        
        public ProveedoresCuentasSoapClient() {
        }
        
        public ProveedoresCuentasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProveedoresCuentasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedoresCuentasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedoresCuentasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetCuentaCorrienteV2(long pUsr) {
            return base.Channel.GetCuentaCorrienteV2(pUsr);
        }
        
        public System.Data.DataSet GetProveedores() {
            return base.Channel.GetProveedores();
        }
        
        public System.Data.DataSet GetUsuarioValidacion(long pUsr) {
            return base.Channel.GetUsuarioValidacion(pUsr);
        }
        
        public System.Data.DataSet SetComprobante(long pCtaId, long pNroCae, long pFecEmi, string pTipCmp, string pNroCmp, decimal pImp, long pUsr) {
            return base.Channel.SetComprobante(pCtaId, pNroCae, pFecEmi, pTipCmp, pNroCmp, pImp, pUsr);
        }
        
        public System.Data.DataSet SetComprobanteV2(string pNroOp, string pTipCmp, string pNroCmp, long pFecEmi, long pNroCae, decimal pImp, long pUsr) {
            return base.Channel.SetComprobanteV2(pNroOp, pTipCmp, pNroCmp, pFecEmi, pNroCae, pImp, pUsr);
        }
    }
}
