//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtranetAppsOmniSerca.WSNotificaciones {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="WSNotificaciones.NotificacionesSoap")]
    public interface NotificacionesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.DeleteMensaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DeleteMensaje(long pMsgId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.GetGruposGerencias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetGruposGerencias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.GetGruposUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetGruposUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.GetMensaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMensaje(long pMsgId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.GetMensajesEmitidos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMensajesEmitidos(long pUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.GetMensajesRecibidos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMensajesRecibidos(long pUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.GetUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUsuarios(long pGrp, long pNotExcId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.GetUsuariosGerencias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUsuariosGerencias(long pGer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.GetUsuariosNotificados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUsuariosNotificados(long pNotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.GetUsuariosPrestadores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUsuariosPrestadores(long pGrp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.SetEstadoMensajeUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SetEstadoMensajeUsuario(long pMsgId, long pUsr, long pEst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.SetMensaje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SetMensaje(long pMsgId, string pMsg, long pUsr, long pMail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.SetMensajeUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SetMensajeUsuarios(long pMsgId, string pUsrList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.Notificaciones.SetMensajeV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SetMensajeV2(long pMsgId, string pMsgRtf, string pMsgTxt, long pUsr, long pMail);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NotificacionesSoapChannel : ExtranetAppsOmniSerca.WSNotificaciones.NotificacionesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificacionesSoapClient : System.ServiceModel.ClientBase<ExtranetAppsOmniSerca.WSNotificaciones.NotificacionesSoap>, ExtranetAppsOmniSerca.WSNotificaciones.NotificacionesSoap {
        
        public NotificacionesSoapClient() {
        }
        
        public NotificacionesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificacionesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificacionesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificacionesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet DeleteMensaje(long pMsgId) {
            return base.Channel.DeleteMensaje(pMsgId);
        }
        
        public System.Data.DataSet GetGruposGerencias() {
            return base.Channel.GetGruposGerencias();
        }
        
        public System.Data.DataSet GetGruposUsuarios() {
            return base.Channel.GetGruposUsuarios();
        }
        
        public string GetMensaje(long pMsgId) {
            return base.Channel.GetMensaje(pMsgId);
        }
        
        public System.Data.DataSet GetMensajesEmitidos(long pUsr) {
            return base.Channel.GetMensajesEmitidos(pUsr);
        }
        
        public System.Data.DataSet GetMensajesRecibidos(long pUsr) {
            return base.Channel.GetMensajesRecibidos(pUsr);
        }
        
        public System.Data.DataSet GetUsuarios(long pGrp, long pNotExcId) {
            return base.Channel.GetUsuarios(pGrp, pNotExcId);
        }
        
        public System.Data.DataSet GetUsuariosGerencias(long pGer) {
            return base.Channel.GetUsuariosGerencias(pGer);
        }
        
        public System.Data.DataSet GetUsuariosNotificados(long pNotId) {
            return base.Channel.GetUsuariosNotificados(pNotId);
        }
        
        public System.Data.DataSet GetUsuariosPrestadores(long pGrp) {
            return base.Channel.GetUsuariosPrestadores(pGrp);
        }
        
        public System.Data.DataSet SetEstadoMensajeUsuario(long pMsgId, long pUsr, long pEst) {
            return base.Channel.SetEstadoMensajeUsuario(pMsgId, pUsr, pEst);
        }
        
        public System.Data.DataSet SetMensaje(long pMsgId, string pMsg, long pUsr, long pMail) {
            return base.Channel.SetMensaje(pMsgId, pMsg, pUsr, pMail);
        }
        
        public System.Data.DataSet SetMensajeUsuarios(long pMsgId, string pUsrList) {
            return base.Channel.SetMensajeUsuarios(pMsgId, pUsrList);
        }
        
        public System.Data.DataSet SetMensajeV2(long pMsgId, string pMsgRtf, string pMsgTxt, long pUsr, long pMail) {
            return base.Channel.SetMensajeV2(pMsgId, pMsgRtf, pMsgTxt, pUsr, pMail);
        }
    }
}
