//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtranetAppsOmniSerca.WSShamanFecae {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSShamanFecae.WSShamanFECAESoap")]
    public interface WSShamanFECAESoap {
        
        // CODEGEN: El parámetro 'GetPDF_CacheResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPDF_Cache", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ExtranetAppsOmniSerca.WSShamanFecae.GetPDF_CacheResponse GetPDF_Cache(ExtranetAppsOmniSerca.WSShamanFecae.GetPDF_CacheRequest request);
        
        // CODEGEN: El parámetro 'GetReportsIncidente_CacheResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportsIncidente_Cache", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ExtranetAppsOmniSerca.WSShamanFecae.GetReportsIncidente_CacheResponse GetReportsIncidente_Cache(ExtranetAppsOmniSerca.WSShamanFecae.GetReportsIncidente_CacheRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCuentaCorriene", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCuentaCorriene(decimal pUsr);
        
        // CODEGEN: El parámetro 'GetCertificadoRetencion_TangoResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCertificadoRetencion_Tango", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ExtranetAppsOmniSerca.WSShamanFecae.GetCertificadoRetencion_TangoResponse GetCertificadoRetencion_Tango(ExtranetAppsOmniSerca.WSShamanFecae.GetCertificadoRetencion_TangoRequest request);
        
        // CODEGEN: El parámetro 'GetContratoVentaResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContratoVenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ExtranetAppsOmniSerca.WSShamanFecae.GetContratoVentaResponse GetContratoVenta(ExtranetAppsOmniSerca.WSShamanFecae.GetContratoVentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPDF_Cache", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPDF_CacheRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal pDocId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal pUsrId;
        
        public GetPDF_CacheRequest() {
        }
        
        public GetPDF_CacheRequest(decimal pDocId, decimal pUsrId) {
            this.pDocId = pDocId;
            this.pUsrId = pUsrId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPDF_CacheResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPDF_CacheResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetPDF_CacheResult;
        
        public GetPDF_CacheResponse() {
        }
        
        public GetPDF_CacheResponse(byte[] GetPDF_CacheResult) {
            this.GetPDF_CacheResult = GetPDF_CacheResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportsIncidente_Cache", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetReportsIncidente_CacheRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal pInc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal pUsrId;
        
        public GetReportsIncidente_CacheRequest() {
        }
        
        public GetReportsIncidente_CacheRequest(decimal pInc, decimal pUsrId) {
            this.pInc = pInc;
            this.pUsrId = pUsrId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReportsIncidente_CacheResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetReportsIncidente_CacheResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetReportsIncidente_CacheResult;
        
        public GetReportsIncidente_CacheResponse() {
        }
        
        public GetReportsIncidente_CacheResponse(byte[] GetReportsIncidente_CacheResult) {
            this.GetReportsIncidente_CacheResult = GetReportsIncidente_CacheResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Certificado {
        
        /// <remarks/>
        crtArba,
        
        /// <remarks/>
        crtAgip,
        
        /// <remarks/>
        crtGanancias,
        
        /// <remarks/>
        crtIVA,
        
        /// <remarks/>
        crtCajaPrevisional,
        
        /// <remarks/>
        crtContratoVenta,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCertificadoRetencion_Tango", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCertificadoRetencion_TangoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pNroOp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ExtranetAppsOmniSerca.WSShamanFecae.Certificado pRetId;
        
        public GetCertificadoRetencion_TangoRequest() {
        }
        
        public GetCertificadoRetencion_TangoRequest(string pNroOp, ExtranetAppsOmniSerca.WSShamanFecae.Certificado pRetId) {
            this.pNroOp = pNroOp;
            this.pRetId = pRetId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCertificadoRetencion_TangoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCertificadoRetencion_TangoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetCertificadoRetencion_TangoResult;
        
        public GetCertificadoRetencion_TangoResponse() {
        }
        
        public GetCertificadoRetencion_TangoResponse(byte[] GetCertificadoRetencion_TangoResult) {
            this.GetCertificadoRetencion_TangoResult = GetCertificadoRetencion_TangoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContratoVenta", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetContratoVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pClienteId;
        
        public GetContratoVentaRequest() {
        }
        
        public GetContratoVentaRequest(string pClienteId) {
            this.pClienteId = pClienteId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContratoVentaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetContratoVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetContratoVentaResult;
        
        public GetContratoVentaResponse() {
        }
        
        public GetContratoVentaResponse(byte[] GetContratoVentaResult) {
            this.GetContratoVentaResult = GetContratoVentaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSShamanFECAESoapChannel : ExtranetAppsOmniSerca.WSShamanFecae.WSShamanFECAESoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSShamanFECAESoapClient : System.ServiceModel.ClientBase<ExtranetAppsOmniSerca.WSShamanFecae.WSShamanFECAESoap>, ExtranetAppsOmniSerca.WSShamanFecae.WSShamanFECAESoap {
        
        public WSShamanFECAESoapClient() {
        }
        
        public WSShamanFECAESoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSShamanFECAESoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSShamanFECAESoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSShamanFECAESoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExtranetAppsOmniSerca.WSShamanFecae.GetPDF_CacheResponse ExtranetAppsOmniSerca.WSShamanFecae.WSShamanFECAESoap.GetPDF_Cache(ExtranetAppsOmniSerca.WSShamanFecae.GetPDF_CacheRequest request) {
            return base.Channel.GetPDF_Cache(request);
        }
        
        public byte[] GetPDF_Cache(decimal pDocId, decimal pUsrId) {
            ExtranetAppsOmniSerca.WSShamanFecae.GetPDF_CacheRequest inValue = new ExtranetAppsOmniSerca.WSShamanFecae.GetPDF_CacheRequest();
            inValue.pDocId = pDocId;
            inValue.pUsrId = pUsrId;
            ExtranetAppsOmniSerca.WSShamanFecae.GetPDF_CacheResponse retVal = ((ExtranetAppsOmniSerca.WSShamanFecae.WSShamanFECAESoap)(this)).GetPDF_Cache(inValue);
            return retVal.GetPDF_CacheResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExtranetAppsOmniSerca.WSShamanFecae.GetReportsIncidente_CacheResponse ExtranetAppsOmniSerca.WSShamanFecae.WSShamanFECAESoap.GetReportsIncidente_Cache(ExtranetAppsOmniSerca.WSShamanFecae.GetReportsIncidente_CacheRequest request) {
            return base.Channel.GetReportsIncidente_Cache(request);
        }
        
        public byte[] GetReportsIncidente_Cache(decimal pInc, decimal pUsrId) {
            ExtranetAppsOmniSerca.WSShamanFecae.GetReportsIncidente_CacheRequest inValue = new ExtranetAppsOmniSerca.WSShamanFecae.GetReportsIncidente_CacheRequest();
            inValue.pInc = pInc;
            inValue.pUsrId = pUsrId;
            ExtranetAppsOmniSerca.WSShamanFecae.GetReportsIncidente_CacheResponse retVal = ((ExtranetAppsOmniSerca.WSShamanFecae.WSShamanFECAESoap)(this)).GetReportsIncidente_Cache(inValue);
            return retVal.GetReportsIncidente_CacheResult;
        }
        
        public System.Data.DataTable GetCuentaCorriene(decimal pUsr) {
            return base.Channel.GetCuentaCorriene(pUsr);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExtranetAppsOmniSerca.WSShamanFecae.GetCertificadoRetencion_TangoResponse ExtranetAppsOmniSerca.WSShamanFecae.WSShamanFECAESoap.GetCertificadoRetencion_Tango(ExtranetAppsOmniSerca.WSShamanFecae.GetCertificadoRetencion_TangoRequest request) {
            return base.Channel.GetCertificadoRetencion_Tango(request);
        }
        
        public byte[] GetCertificadoRetencion_Tango(string pNroOp, ExtranetAppsOmniSerca.WSShamanFecae.Certificado pRetId) {
            ExtranetAppsOmniSerca.WSShamanFecae.GetCertificadoRetencion_TangoRequest inValue = new ExtranetAppsOmniSerca.WSShamanFecae.GetCertificadoRetencion_TangoRequest();
            inValue.pNroOp = pNroOp;
            inValue.pRetId = pRetId;
            ExtranetAppsOmniSerca.WSShamanFecae.GetCertificadoRetencion_TangoResponse retVal = ((ExtranetAppsOmniSerca.WSShamanFecae.WSShamanFECAESoap)(this)).GetCertificadoRetencion_Tango(inValue);
            return retVal.GetCertificadoRetencion_TangoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExtranetAppsOmniSerca.WSShamanFecae.GetContratoVentaResponse ExtranetAppsOmniSerca.WSShamanFecae.WSShamanFECAESoap.GetContratoVenta(ExtranetAppsOmniSerca.WSShamanFecae.GetContratoVentaRequest request) {
            return base.Channel.GetContratoVenta(request);
        }
        
        public byte[] GetContratoVenta(string pClienteId) {
            ExtranetAppsOmniSerca.WSShamanFecae.GetContratoVentaRequest inValue = new ExtranetAppsOmniSerca.WSShamanFecae.GetContratoVentaRequest();
            inValue.pClienteId = pClienteId;
            ExtranetAppsOmniSerca.WSShamanFecae.GetContratoVentaResponse retVal = ((ExtranetAppsOmniSerca.WSShamanFecae.WSShamanFECAESoap)(this)).GetContratoVenta(inValue);
            return retVal.GetContratoVentaResult;
        }
    }
}
