//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtranetAppsOmniSerca.WSClientesDocumentos {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="WSClientesDocumentos.ClientesDocumentosSoap")]
    public interface ClientesDocumentosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.ClientesDocumentos.GetComprobantes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetComprobantes(long pUsr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.ClientesDocumentos.GetCuentaCorriente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCuentaCorriente(long pCli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.ClientesDocumentos.GetServicioRenglon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetServicioRenglon(long pUsr, long pDoc, long pInc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.ClientesDocumentos.GetServiciosComprobantes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetServiciosComprobantes(long pUsr, long pDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.ClientesDocumentos.GetUsuarioValidacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUsuarioValidacion(long pUsr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientesDocumentosSoapChannel : ExtranetAppsOmniSerca.WSClientesDocumentos.ClientesDocumentosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesDocumentosSoapClient : System.ServiceModel.ClientBase<ExtranetAppsOmniSerca.WSClientesDocumentos.ClientesDocumentosSoap>, ExtranetAppsOmniSerca.WSClientesDocumentos.ClientesDocumentosSoap {
        
        public ClientesDocumentosSoapClient() {
        }
        
        public ClientesDocumentosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesDocumentosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesDocumentosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesDocumentosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetComprobantes(long pUsr) {
            return base.Channel.GetComprobantes(pUsr);
        }
        
        public string GetCuentaCorriente(long pCli) {
            return base.Channel.GetCuentaCorriente(pCli);
        }
        
        public System.Data.DataSet GetServicioRenglon(long pUsr, long pDoc, long pInc) {
            return base.Channel.GetServicioRenglon(pUsr, pDoc, pInc);
        }
        
        public System.Data.DataSet GetServiciosComprobantes(long pUsr, long pDoc) {
            return base.Channel.GetServiciosComprobantes(pUsr, pDoc);
        }
        
        public System.Data.DataSet GetUsuarioValidacion(long pUsr) {
            return base.Channel.GetUsuarioValidacion(pUsr);
        }
    }
}
